scope: postgres
namespace: /postgres-cluster/
name: postgres-node-master

restapi:
  listen: 164.92.209.16:8008
  connect_address: 164.92.209.16:8008

etcd:
  hosts: 128.199.48.121:2379,128.199.44.80:2379,128.199.46.145:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
    wal_level: replica
    hot_standby: "on"
    max_wal_senders: 5
    max_replication_slots: 5
    wal_log_hints: "on"
    archive_mode: "on"
    archive_timeout: 600s
    archive_command: "cp -f %p /db/pg_archived/%f"
    recovery_conf:
      restore_command: "cp -f /db/pg_archived/%f %p"
  initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF8
  # init pg_hba.conf должен содержать адреса ВСЕХ машин, используемых в кластере
  pg_hba:
    - host replication replicator     ::1/128            md5
    - host replication replicator     127.0.0.1/8        md5
    - host replication replicator     164.92.209.16/24  md5
    - host replication replicator     167.172.39.167/24  md5
    - host replication replicator     128.199.47.98/24 md5
    - host replication replicator     128.199.46.171/24 md5
    - host all         rebrain_admin  0.0.0.0/0          md5
    - host all         root           0.0.0.0/0          md5
  users:
    rebrain_admin:
      password: pwd

postgresql:
  listen: 164.92.209.16:5432
  connect_address: 164.92.209.16:5432
  data_dir: /etc/patroni/pgdata
  bin_dir: /usr/lib/postgresql/15/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: replicatorSuperHarDpwd
    superuser:
      username: root
      password: admin
  create_replica_methods:
    basebackup:
      checkpoint: "fast"
  parameters:
    unix_socket_directories: "/var/run/postgresql"
    external_pid_file: "/var/run/postgresql/15-main.pid"
  logging_collector: "on"
  log_directory: "/var/log/postgresql"
  log_filename: "postgresql-15-main.log"
